Repository lanl/bml, pull requests merged in 2018-08, with the labels that each got.

#222 Introduce build stages
  .travis.yml
  install_packages.sh
Labels: enhancement, review

#223 Fix the Travis-CI coverage test
  .travis.yml
Labels: bug, review

#224 Only test on build for memory leaks
  .travis.yml
Labels: enhancement, review

#225 More tests
  .travis.yml
Labels: enhancement, review

#226 Conditional build of docs
  .travis.yml
Labels: enhancement, review

#221 Generalize matrix dimensions (Issue #220)
  src/C-interface/bml_allocate.c
  src/C-interface/bml_allocate.h
  src/C-interface/bml_types.h
  src/C-interface/dense/bml_allocate_dense.c
  src/C-interface/dense/bml_allocate_dense.h
  src/C-interface/dense/bml_allocate_dense_typed.c
  src/C-interface/dense/bml_convert_dense_typed.c
  src/C-interface/dense/bml_copy_dense_typed.c
  src/C-interface/dense/bml_import_dense_typed.c
  src/C-interface/dense/bml_threshold_dense_typed.c
  src/C-interface/dense/bml_transpose_dense_typed.c
  src/C-interface/ellpack/bml_allocate_ellpack.c
  src/C-interface/ellpack/bml_allocate_ellpack.h
  src/C-interface/ellpack/bml_allocate_ellpack_typed.c
  src/C-interface/ellpack/bml_copy_ellpack_typed.c
  src/C-interface/ellpack/bml_multiply_ellpack_typed.c
  src/C-interface/ellpack/bml_submatrix_ellpack_typed.c
  src/C-interface/ellpack/bml_transpose_ellpack_typed.c
  src/C-interface/ellsort/bml_allocate_ellsort.c
  src/C-interface/ellsort/bml_allocate_ellsort.h
  src/C-interface/ellsort/bml_allocate_ellsort_typed.c
  src/C-interface/ellsort/bml_copy_ellsort_typed.c
  src/C-interface/ellsort/bml_multiply_ellsort_typed.c
  src/C-interface/ellsort/bml_submatrix_ellsort_typed.c
  src/C-interface/ellsort/bml_transpose_ellsort_typed.c
Labels: review

#227 Re-add coverty scan
  .travis.yml
Labels: review

#229 Stricter linting
  Dangerfile
Labels: review

#230 Run only coverty_scan stage
  .travis.yml
Labels: review

#228 Magma
  CMakeLists.txt
  build.sh
  cmake/FindMAGMA.cmake
  magma_build.sh
  src/C-interface/bml_init.c
  src/C-interface/bml_shutdown.c
  src/C-interface/dense/bml_add_dense_typed.c
  src/C-interface/dense/bml_allocate_dense.c
  src/C-interface/dense/bml_allocate_dense_typed.c
  src/C-interface/dense/bml_convert_dense_typed.c
  src/C-interface/dense/bml_copy_dense_typed.c
  src/C-interface/dense/bml_diagonalize_dense.c
  src/C-interface/dense/bml_export_dense.c
  src/C-interface/dense/bml_export_dense_typed.c
  src/C-interface/dense/bml_getters_dense_typed.c
  src/C-interface/dense/bml_import_dense_typed.c
  src/C-interface/dense/bml_introspection_dense_typed.c
  src/C-interface/dense/bml_inverse_dense_typed.c
  src/C-interface/dense/bml_multiply_dense_typed.c
  src/C-interface/dense/bml_norm_dense_typed.c
  src/C-interface/dense/bml_normalize_dense_typed.c
  src/C-interface/dense/bml_scale_dense_typed.c
  src/C-interface/dense/bml_setters_dense_typed.c
  src/C-interface/dense/bml_threshold_dense_typed.c
  src/C-interface/dense/bml_trace_dense_typed.c
  src/C-interface/dense/bml_transpose_dense_typed.c
  src/C-interface/dense/bml_types_dense.h
  src/C-interface/dense/bml_utilities_dense.c
  src/C-interface/dense/bml_utilities_dense.h
  src/C-interface/dense/bml_utilities_dense_typed.c
  src/C-interface/ellpack/bml_submatrix_ellpack_typed.c
  src/C-interface/ellsort/bml_submatrix_ellsort_typed.c
  src/typed.h
  tests/CMakeLists.txt
  tests/threshold_matrix_typed.c
Labels: enhancement
