Repository lanl/bml, pull requests merged in 2019-05, with the labels that each got.

#252 Added missing argument when compiling with magma and omp
  src/C-interface/dense/bml_normalize_dense_typed.c
Labels: review

#253 Add Jean-Luc as code reviewer
  CODEOWNERS
Labels: review

#255 Make build of complex types optional
  CMakeLists.txt
  build.sh
  cmake/test_complex.c
  src/typed.h
Labels: bug, review

#249 fixed omp index issue in bml_multiply_ellsort_typed.c
  src/C-interface/ellsort/bml_multiply_ellsort_typed.c
Labels: review

#259 Print CMake version (for debugging)
  CMakeLists.txt
Labels: enhancement
